### ISSUE TITLE
Update Alastria-identity-lib version (use develop version)

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastria-wallet#106]
The backend should use the [develop](https://github.com/alastria/alastria-identity-lib/tree/develop) version of alastria-identity-lib.

**This may involve adapting the code to use the new version of the library.**

**Comment by Ocarazo** [comment]
I'm facing this problem when i try to start the application with `npm run start:browser`
![Captura de pantalla de 2021-12-03 12-48-02](https://user-images.githubusercontent.com/74591667/144598200-41563f79-c7f2-4b15-84a4-688767cd257e.png)

**Comment by VictorNS69** [comment]
I think the error is that you are using  `transactionFactory.identityManager.getEntity` instead of `transactionFactory.alastriaNameService.getEntity`
See this example: https://github.com/alastria/alastria-identity-example/blob/develop/exampleEntities/2.getEntity.js#L20
