### ISSUE TITLE
Api keys uploaded

### ISSUE THREAD

**Issue by zerjioang** [alastria/alastria-wallet#4]
Hi,

I notice you have uploaded secret material (api keys, etc) to github. This goes against best practises for developers. Usual recomendation is to keep them in a separate enviroment file that it is not commited to vcs.

Affected files:
https://github.com/alastria/alastria-wallet/blob/master/src/services/app-settings.ts

**Comment by esanchma** [comment]
At this point, the wallet does not have any firebase integration (we don't have push notifications, right?), however, @oscargonzalezmoreno, can you review this? I highly suggest using https://www.npmjs.com/package/dotenv to manage API credentials, all kind of bots are scrapping github looking for secrets.

**Comment by esanchma** [comment]
That file is in the template (ie: https://csform.com/documentation-for-ionic-3-ui-template-app-green-light/ ) and is not a real credential, just an example. Closing as invalid.
