### ISSUE TITLE
Android device deploy

### ISSUE THREAD

**Issue by ChristianTaidi** [alastria/alastria-wallet#49]
#### When I  try to run the wallet in a physical device using Android 10 I get an error when starting the app, it installs successfully in the device but does not run throwing the following error
 ` The connection to the server was unsuccessful (file:///android_asset/www/index.html) `

### Using
- cordova 9.0.0
- Android SDK 28 and latest build tools
- npm 5.6.0
- node 10.0.0

**Comment by JuanLuisGozaloFdez** [comment]
HI, Cristian. 
Sorry for the big delay to reply to you. 
The error may be is due to a problem with the Demo Server we are using to help people to demonstrate the wallet.
Please let us know if your error is still ahppening.

**Comment by VictorNS69** [comment]
I close this issue until further notice. 
If the problem persists, feel free to reopen the issue

**Comment by ChristianTaidi** [comment]
Hello, sorry for not replying, I was trying to replicate the environment to develop my thesis on a blockhain based KYC process, i developed a wallet and an environment by myself but I will test this system in case it wors to continue with the project development. I would also like to participate in the Alastria project so when I have managed to replicate the whole system and understand it´s inner workings, maybe I could include some of my ideas.
Thank you very much
