### ISSUE TITLE
Error al intentar arrancar el wallet desde Ubuntu 18.04

### ISSUE THREAD

**Issue by cmoralesdiego** [alastria/alastria-wallet#76]
Buenas, 

Tras seguir los pasos indicados por @agomezlyte para arrancar el wallet. Otro de los problemas que tenemos es el que adjunto en la captura de pantalla
![CapturaAlastria](https://user-images.githubusercontent.com/63613919/89032518-21adff00-d335-11ea-9779-d57850187dbf.PNG)

No sabemos si es por el hecho de usar una máquina virtual o por qué, pero nos muestra este error, pero no nos deja continuar. Muchas gracias!!!!

**Comment by cmoralesdiego** [comment]
Buenas, alguna idea sobre este error que nos está dando?. Hemos vuelto a empezar de 0 instalando todo nuevamente....y lo mismo, alguna idea?. Gracias

**Comment by rdemera** [comment]
Yo he tenido el mismo problema

La issue viene de cuando se crea el SecureStorage: this.securedStorage.create("identitySecureStorage)

**Comment by rbarriuso** [comment]
El problema parece ser debido a esta issue: https://github.com/mibrito707/cordova-plugin-secure-storage-echo/issues/58

He creado esta PR como propuesta para solucionarlo: https://github.com/alastria/alastria-wallet/pull/78

**Comment by rdemera** [comment]
This issue is solved with the changes made by @rbarriuso in #78
