### ISSUE TITLE
Problema de compilación

### ISSUE THREAD

**Issue by jcarovestigia** [alastria/alastria-wallet#82]
En src/index.js dice 
const library = require('../dist/index.js')

pero ../dist parece que no existe

¿Hay algún error?

**Comment by VictorNS69** [comment]
Hola @rdemera te suena de algo este error? Creo que tiene más que ver con el wallet. No sé si la versión (o rama) que está usando @jcarovestigia es la indicada.

**Comment by jcarovestigia** [comment]
Perdón. No entiendo mucho de esto, pero parece apuntar a develop (ver https://github.com/alastria/alastria-wallet/blob/master/package.json). Esto me ha extrañado.

**Comment by rdemera** [comment]
Hola @jcarovestigia si quieres probar con el wallet tienes que usar la rama de develop

https://github.com/alastria/alastria-wallet/tree/develop

**Comment by rdemera** [comment]
@jcarovestigia  En wallet importamos como depencia la librería de identidad directamente desde el repo de github (alastria-identity-lib), con el # indicamos la rama que deseamos usar.

**Comment by jcarovestigia** [comment]
Muchas gracias. Después de pasarme a linux y probar con varias versiones, he dado con una combinación capaz de compilar el proyecto.

**Comment by rdemera** [comment]
@jcarovestigia Genial! Cierro la issue, si tienes alguna duda no dudes en preguntar.
