### ISSUE TITLE
Git clone alastria-identity.git : too many arguments

### ISSUE THREAD

**Issue by glalloue** [alastria/alastria-wallet#86]
Hello,

I cloned alastria-wallet repository and i'm trying to make it running.
But i receive this error : 

> alastria-identity-lib@1.5.0 compile D:\projets\alastria-wallet\node_modules\alastria-identity-lib
> git clone --branch mvp0.1 https://github.com/alastria/alastria-identity.git; node src/configFile.js; tsc
> 
> fatal: Too many arguments.

**Steps to reproduce :** 

> git clone https://github.com/alastria/alastria-wallet.git
> git checkout develop
> npm install

**Sources information :** 
Last commit on develop is "Merge pull request #85 from alastria/feature/updateReadme"

**Technical environment :** 
- Windows 10 x64
- node v10.15.3
- python 2.7.15
- npm 6.13.4 (also tried with yarn)

**Comment by rbarriuso** [comment]
I think this issue belongs to https://github.com/alastria/alastria-identity, not in this repo.

The `compile` script is defined in [package.json of `alastria-identity-lib`](https://github.com/alastria/alastria-identity-lib/blob/develop/package.json#L12) as:
```
"compile": "git clone --branch mvp0.1 https://github.com/alastria/alastria-identity.git; node src/configFile.js; tsc",
```

But in Windows the character `;` is a paeter separator instead of a command separator. It should be defined as:
```
"compile": "git clone --branch mvp0.1 https://github.com/alastria/alastria-identity.git && node src/configFile.js && tsc",
```

**Comment by glalloue** [comment]
I confirm the identification of the problem.
While waiting for the fix I use the following workaround:

- local download of the alastria-identity-lib library (develop branch

- Modification of the "package.json" file of the alastria-identity-lib lib:
Replace:
`"compile": "git clone --branch mvp0.1 https://github.com/alastria/alastria-identity.git; node src / configFile.js; tsc",`
Through :
`"compile": "git clone --branch mvp0.1 https://github.com/alastria/alastria-identity.git && node src / configFile.js && tsc",`

- In the package.json file, directly use the local lib
`"alastria-identity-lib": "file: ./ alastria-identity-lib-develop",`

The compilation works perfectly
