### ISSUE TITLE
configuration information missing : update README

### ISSUE THREAD

**Issue by glalloue** [alastria/alastria-wallet#87]
Hello,

I followed the README informations to build and launch alastria wallet.
But i found some missing informations : 

**1. Link to issue is not necessary anymore :** 
`**AFTER INSTALLATION: it is necessary to do this: https://github.com/auth0/node-jsonwebtoken/issues/471#issuecomment-398798497`
This issue is closed and and new version file contain this default settings : 
_file name : node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js_
`node: {crypto: true, stream: true},`
**EDIT** : see if `buffer: true` is necessary to add

**2. No documentation to create AlastriaId and test alastria-wallet**
I can launch alastra-wallet on browser and android device but i did not found any informations about how to create Alastria ID and use it on app. So i cannot sayt if this project is working well right now.

**3. Server URL seems to be unavailable**
Looking at the code, i found SERVER_URL setting = http://34.244.47.233:10011
I suppose this is url where i can create account, but this url is not accessible : 

![image](https://user-images.githubusercontent.com/10628710/100898831-7323f180-34c1-11eb-8d14-9e877cedaf6e.png)

**4. How to configure alastria-wallet project ?**
I have alastriaEntity installed locally and can create local account.
But i have no idea how to configure my alastria-wallet local project to access to it and fill settings.
It could be good idea to update readme to explain how to configure project with our settings.
Here some files that i listed that i think i need to modify : 

- replace IP address for SERVER_URL
`src/app/services/socket.service.ts`
- replace IP address for nodeURL 
`~/alastria-wallet/src/app.config.ts`
- replace entityUrl
`src/assets/mocks/entities.json`
- replace contracts addresses 
`node_modules/alastria-identity-lib/src/config.ts`
- replace contract addresses
`node_modules/alastria-identity-lib/alastria-identity/contracts/ContractInfo.md`

**Technical environment :**

Windows 10 x64
node v10.15.3
python 2.7.15
npm 6.13.4
yarn 1.21.1

**Comment by rdemera** [comment]
Issue solved with Pr #94
