### ISSUE TITLE
getCurrentPublicKey from TransactionService return 'Returned values aren't valid, did it run Out of Gas?' error

### ISSUE THREAD

**Issue by glalloue** [alastria/alastria-wallet#88]
Hello,

I am not able to make alastria-wallet work with the alastria server.
Here is the reason : 

Alastria server generate QR Code.
When i try to scan this QRCode with my Ionic app, app display error page : 

![image](https://user-images.githubusercontent.com/10628710/101513430-7533f780-397c-11eb-9fb5-2046844a89b3.png)

Logs : 
`
null: Error -------->
null: Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced. -- transaction-service.ts:50
`

**Analysis :** 
Error is from `TransactionService.getCurrentPublicKey()` method.
Call stack is : 
- camera.ts.ionViewWillEnter
- MessageManagerService.prepareDataAndInit
- MessageManagerService.launchProtocol
- MessageManagerService.createAndSendAlastriaAIC
- this.transactionSrv.getCurrentPublicKey(web3, issuerDID)

```
return web3.eth.call(currentPubKey)
            .then(result => {
                const pubKey = web3.eth.abi.decodeParameters(['string'], result);
                const publicKey = pubKey[0];
                return publicKey;
            })
            .catch(error => {
                console.error('Error -------->', error);
            });`
```
web3.ath call enter to success callback with result value = "0x"
Then, error happen on next line : 
`const pubKey = web3.eth.abi.decodeParameters(['string'], result);`

Information : GWU url passed to getWeb3 function is our local Alastria server url

Do i need to change configuration somewhere to make it running ?

I changed this data on code to make it running with our server url : 
•	replace IP address for SERVER_URL
File: src/app/services/socket.service.ts
Replace :
const SERVER_URL = 'http://34.244.47.233:10011';

•	replace IP address for nodeURL 
File: src/app/app.config.ts
replace:
public static readonly nodeURL = 'http://63.33.206.111/rpc';

•	replace entityUrl
File src/assets/mocks/entities.json
Replace :
"entityUrl": "http://34.244.47.233/vinculate",

**Technical environment :**

Windows 10 x64
node v10.15.3
python 2.7.15
npm 6.13.4
yarn 1.21.1

**Comment by glalloue** [comment]
I close this issue, there is no error in this part of code

**Comment by glalloue** [comment]
I updated ticket with error details.
Hope you will be able to explain me problem origin ;)

**Comment by rdemera** [comment]
Thanks for reporting @glalloue , we will try to review and reproduce the issue.

**Comment by rdemera** [comment]
Alastria porvides access to:

Alastria Identity node: http://63.33.206.111/rpc
Alastria Entity: http://34.244.47.233/vinculate

With this resources you can be able to create a new Alastria Id, and complete the mvp specs.
